title: Sunny Oswal
description: >
  Software Engineer. Microsoft Azure Enthusiast. Go-Getter.
theme: jekyll-theme-cayman
google_analytics: UA-145067209-1
google_ad_client: ca-pub-8924066507492142
plugins:
  - jemoji
twitter_url: https://twitter.com/sunny_oswal
linkedin_url:	https://www.linkedin.com/in/sunny-oswal-1a153a49/
