title: Sunny Oswal
description: >
  Software Engineer. Cloud Computing Enthusiast. DevOps. Go-Getter.
theme: jekyll-theme-time-machine
google_analytics: UA-145067209-1
google_ad_client: ca-pub-8924066507492142
paginate: 4
plugins:
  - jemoji
twitter_url: https://twitter.com/sunny_oswal
linkedin_url:	https://www.linkedin.com/in/sunny-oswal-1a153a49/
